name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: self-hosted
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: 4l3j0Ok/metrics@master
        with:
          token: ${{ secrets.GH_PAT }}
          filename: public/github-metrics.svg
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_isocalendar: yes
          plugin_languages: yes
          use_prebuilt_image: no
